//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.24 at 12:04:02 PM CEST 
//


package decomposition.buildgraph;

import java.util.ArrayList;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="token" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sentence" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Markables" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FOCUS" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="focus_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="FRAGMENT" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="implicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="implicit_reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="implicit_focus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="modality" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="correct_text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MODIFIER" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Relations" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ENTAILS" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EQUIVALENT" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BEFORE" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="doc_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "token",
    "markables",
    "relations"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(nillable = true)
    protected List<Document.Token> token;
    @XmlElement(name = "Markables")
    protected List<Document.Markables> markables;
    @XmlElement(name = "Relations")
    protected List<Document.Relations> relations;
    @XmlAttribute(name = "doc_name")
    protected String docName;

    /**
     * Gets the value of the token property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the token property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToken().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document.Token }
     * 
     * 
     */
    public List<Document.Token> getToken() {
        if (token == null) {
            token = new ArrayList<Document.Token>();
        }
        return this.token;
    }

    /**
     * Gets the value of the markables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document.Markables }
     * 
     * 
     */
    public List<Document.Markables> getMarkables() {
        if (markables == null) {
            markables = new ArrayList<Document.Markables>();
        }
        return this.markables;
    }

    /**
     * Gets the value of the relations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document.Relations }
     * 
     * 
     */
    public List<Document.Relations> getRelations() {
        if (relations == null) {
            relations = new ArrayList<Document.Relations>();
        }
        return this.relations;
    }

    /**
     * Gets the value of the docName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocName() {
        return docName;
    }

    /**
     * Sets the value of the docName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocName(String value) {
        this.docName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FOCUS" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="focus_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FRAGMENT" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="implicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="implicit_reason" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="implicit_focus" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="modality" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="correct_text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MODIFIER" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "focus",
        "fragment",
        "modifier"
    })
    public static class Markables {

        @XmlElement(name = "FOCUS")
        protected List<Document.Markables.FOCUS> focus;
        @XmlElement(name = "FRAGMENT")
        protected List<Document.Markables.FRAGMENT> fragment;
        @XmlElement(name = "MODIFIER")
        protected List<Document.Markables.MODIFIER> modifier;

        /**
         * Gets the value of the focus property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the focus property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFOCUS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Markables.FOCUS }
         * 
         * 
         */
        public List<Document.Markables.FOCUS> getFOCUS() {
            if (focus == null) {
                focus = new ArrayList<Document.Markables.FOCUS>();
            }
            return this.focus;
        }

        /**
         * Gets the value of the fragment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fragment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFRAGMENT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Markables.FRAGMENT }
         * 
         * 
         */
        public List<Document.Markables.FRAGMENT> getFRAGMENT() {
            if (fragment == null) {
                fragment = new ArrayList<Document.Markables.FRAGMENT>();
            }
            return this.fragment;
        }

        /**
         * Gets the value of the modifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the modifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMODIFIER().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Markables.MODIFIER }
         * 
         * 
         */
        public List<Document.Markables.MODIFIER> getMODIFIER() {
            if (modifier == null) {
                modifier = new ArrayList<Document.Markables.MODIFIER>();
            }
            return this.modifier;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="focus_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tokenAnchor"
        })
        public static class FOCUS {

            @XmlElement(name = "token_anchor")
            protected List<TokenAnchor> tokenAnchor;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "focus_ref")
            protected String focusRef;

            /**
             * Gets the value of the tokenAnchor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tokenAnchor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTokenAnchor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TokenAnchor }
             * 
             * 
             */
            public List<TokenAnchor> getTokenAnchor() {
                if (tokenAnchor == null) {
                    tokenAnchor = new ArrayList<TokenAnchor>();
                }
                return this.tokenAnchor;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the focusRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFocusRef() {
                return focusRef;
            }

            /**
             * Sets the value of the focusRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFocusRef(String value) {
                this.focusRef = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="implicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="implicit_reason" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="implicit_focus" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="modality" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="correct_text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tokenAnchor"
        })
        public static class FRAGMENT {

            @XmlElement(name = "token_anchor")
            protected List<TokenAnchor> tokenAnchor;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "implicit_context")
            protected String implicitContext;
            @XmlAttribute(name = "implicit_statement")
            protected String implicitReason;
            @XmlAttribute(name = "implicit_focus")
            protected String implicitFocus;
            @XmlAttribute(name = "modality")
            protected String modality;
            @XmlAttribute(name = "correct_text")
            protected String correctText;

            /**
             * Gets the value of the tokenAnchor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tokenAnchor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTokenAnchor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TokenAnchor }
             * 
             * 
             */
            public List<TokenAnchor> getTokenAnchor() {
                if (tokenAnchor == null) {
                    tokenAnchor = new ArrayList<TokenAnchor>();
                }
                return this.tokenAnchor;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the implicitContext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImplicitContext() {
                return implicitContext;
            }

            /**
             * Sets the value of the implicitContext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImplicitContext(String value) {
                this.implicitContext = value;
            }

            /**
             * Gets the value of the implicitReason property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImplicitReason() {
                return implicitReason;
            }

            /**
             * Sets the value of the implicitReason property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImplicitReason(String value) {
                this.implicitReason = value;
            }

            /**
             * Gets the value of the implicitFocus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImplicitFocus() {
                return implicitFocus;
            }

            /**
             * Sets the value of the implicitFocus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImplicitFocus(String value) {
                this.implicitFocus = value;
            }

            /**
             * Gets the value of the modality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModality() {
                return modality;
            }

            /**
             * Sets the value of the modality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModality(String value) {
                this.modality = value;
            }

            /**
             * Gets the value of the correctText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCorrectText() {
                return correctText;
            }

            /**
             * Sets the value of the correctText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCorrectText(String value) {
                this.correctText = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}token_anchor" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tokenAnchor"
        })
        public static class MODIFIER {

            @XmlElement(name = "token_anchor")
            protected List<TokenAnchor> tokenAnchor;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the tokenAnchor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tokenAnchor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTokenAnchor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TokenAnchor }
             * 
             * 
             */
            public List<TokenAnchor> getTokenAnchor() {
                if (tokenAnchor == null) {
                    tokenAnchor = new ArrayList<TokenAnchor>();
                }
                return this.tokenAnchor;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ENTAILS" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EQUIVALENT" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BEFORE" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entails",
        "equivalent",
        "before"
    })
    public static class Relations {

        @XmlElement(name = "ENTAILS")
        protected List<Document.Relations.ENTAILS> entails;
        @XmlElement(name = "EQUIVALENT")
        protected List<Document.Relations.EQUIVALENT> equivalent;
        @XmlElement(name = "BEFORE")
        protected List<Document.Relations.BEFORE> before;

        /**
         * Gets the value of the entails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getENTAILS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Relations.ENTAILS }
         * 
         * 
         */
        public List<Document.Relations.ENTAILS> getENTAILS() {
            if (entails == null) {
                entails = new ArrayList<Document.Relations.ENTAILS>();
            }
            return this.entails;
        }

        /**
         * Gets the value of the equivalent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the equivalent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEQUIVALENT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Relations.EQUIVALENT }
         * 
         * 
         */
        public List<Document.Relations.EQUIVALENT> getEQUIVALENT() {
            if (equivalent == null) {
                equivalent = new ArrayList<Document.Relations.EQUIVALENT>();
            }
            return this.equivalent;
        }

        /**
         * Gets the value of the before property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the before property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBEFORE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Document.Relations.BEFORE }
         * 
         * 
         */
        public List<Document.Relations.BEFORE> getBEFORE() {
            if (before == null) {
                before = new ArrayList<Document.Relations.BEFORE>();
            }
            return this.before;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source",
            "target"
        })
        public static class BEFORE {

            protected List<Source> source;
            protected List<Target> target;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the source property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the source property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSource().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Source }
             * 
             * 
             */
            public List<Source> getSource() {
                if (source == null) {
                    source = new ArrayList<Source>();
                }
                return this.source;
            }

            /**
             * Gets the value of the target property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the target property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTarget().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Target }
             * 
             * 
             */
            public List<Target> getTarget() {
                if (target == null) {
                    target = new ArrayList<Target>();
                }
                return this.target;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source",
            "target"
        })
        public static class ENTAILS {

            protected List<Source> source;
            protected List<Target> target;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the source property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the source property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSource().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Source }
             * 
             * 
             */
            public List<Source> getSource() {
                if (source == null) {
                    source = new ArrayList<Source>();
                }
                return this.source;
            }

            /**
             * Gets the value of the target property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the target property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTarget().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Target }
             * 
             * 
             */
            public List<Target> getTarget() {
                if (target == null) {
                    target = new ArrayList<Target>();
                }
                return this.target;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}source" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{}target" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "source",
            "target"
        })
        public static class EQUIVALENT {

            protected List<Source> source;
            protected List<Target> target;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the source property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the source property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSource().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Source }
             * 
             * 
             */
            public List<Source> getSource() {
                if (source == null) {
                    source = new ArrayList<Source>();
                }
                return this.source;
            }

            /**
             * Gets the value of the target property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the target property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTarget().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Target }
             * 
             * 
             */
            public List<Target> getTarget() {
                if (target == null) {
                    target = new ArrayList<Target>();
                }
                return this.target;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sentence" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Token {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "sentence")
        protected String sentence;
        @XmlAttribute(name = "number")
        protected String number;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the sentence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSentence() {
            return sentence;
        }

        /**
         * Sets the value of the sentence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSentence(String value) {
            this.sentence = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumber(String value) {
            this.number = value;
        }

    }

}
