//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 11:32:00 AM CEST 
//


package decomposition.buildgraph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="original_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="correct_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="modifiers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="implicit_statement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="modality" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="explicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="implicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="focus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="implicit_focus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="edge" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entailment_mod_insensitive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="entailment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="nodeNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "node",
    "edge"
})
@XmlRootElement(name = "F_entailment_graph")
public class FEntailmentGraph {

    protected List<FEntailmentGraph.Node> node;
    protected List<FEntailmentGraph.Edge> edge;
    @XmlAttribute(name = "nodeNum")
    protected String nodeNum;

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FEntailmentGraph.Node }
     * 
     * 
     */
    public List<FEntailmentGraph.Node> getNode() {
        if (node == null) {
            node = new ArrayList<FEntailmentGraph.Node>();
        }
        return this.node;
    }

    /**
     * Gets the value of the edge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FEntailmentGraph.Edge }
     * 
     * 
     */
    public List<FEntailmentGraph.Edge> getEdge() {
        if (edge == null) {
            edge = new ArrayList<FEntailmentGraph.Edge>();
        }
        return this.edge;
    }

    /**
     * Gets the value of the nodeNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeNum() {
        return nodeNum;
    }

    /**
     * Sets the value of the nodeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeNum(String value) {
        this.nodeNum = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entailment_mod_insensitive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="entailment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entailmentModInsensitive",
        "entailment"
    })
    public static class Edge {

        @XmlElement(name = "entailment_mod_insensitive")
        protected String entailmentModInsensitive;
        @XmlElement(nillable = true)
        protected List<FEntailmentGraph.Edge.Entailment> entailment;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "source")
        protected String source;
        @XmlAttribute(name = "target")
        protected String target;

        /**
         * Gets the value of the entailmentModInsensitive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntailmentModInsensitive() {
            return entailmentModInsensitive;
        }

        /**
         * Sets the value of the entailmentModInsensitive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntailmentModInsensitive(String value) {
            this.entailmentModInsensitive = value;
        }

        /**
         * Gets the value of the entailment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entailment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntailment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FEntailmentGraph.Edge.Entailment }
         * 
         * 
         */
        public List<FEntailmentGraph.Edge.Entailment> getEntailment() {
            if (entailment == null) {
                entailment = new ArrayList<FEntailmentGraph.Edge.Entailment>();
            }
            return this.entailment;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Entailment {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="original_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="correct_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="modifiers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="implicit_statement" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="modality" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="explicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="implicit_context" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="focus" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="implicit_focus" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalText",
        "correctText",
        "modifiers"
    })
    public static class Node {

        @XmlElement(name = "original_text")
        protected String originalText;
        @XmlElement(name = "correct_text")
        protected String correctText;
        @XmlElement(name = "modifiers")
        protected String modifiers;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "implicit_statement")
        protected String implicitStatement;
        @XmlAttribute(name = "modality")
        protected String modality;
        @XmlAttribute(name = "explicit_context")
        protected String explicitContext;
        @XmlAttribute(name = "implicit_context")
        protected String implicitContext;
        @XmlAttribute(name = "focus")
        protected String focus;
        @XmlAttribute(name = "implicit_focus")
        protected String implicitFocus;

        /**
         * Gets the value of the originalText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalText() {
            return originalText;
        }

        /**
         * Sets the value of the originalText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalText(String value) {
            this.originalText = value;
        }

        /**
         * Gets the value of the correctText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCorrectText() {
            return correctText;
        }

        /**
         * Sets the value of the correctText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCorrectText(String value) {
            this.correctText = value;
        }
        
        /**
         * Gets the value of the modifiers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getmodifiers() {
            return modifiers;
        }

        /**
         * Sets the value of the modifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setmodifiers(String value) {
            this.modifiers = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the implicitStatement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImplicitStatement() {
            return implicitStatement;
        }

        /**
         * Sets the value of the implicitStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplicitStatement(String value) {
            this.implicitStatement = value;
        }

        /**
         * Gets the value of the modality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModality() {
            return modality;
        }

        /**
         * Sets the value of the modality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModality(String value) {
            this.modality = value;
        }

        /**
         * Gets the value of the explicitContext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExplicitContext() {
            return explicitContext;
        }

        /**
         * Sets the value of the explicitContext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExplicitContext(String value) {
            this.explicitContext = value;
        }

        /**
         * Gets the value of the implicitContext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImplicitContext() {
            return implicitContext;
        }

        /**
         * Sets the value of the implicitContext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplicitContext(String value) {
            this.implicitContext = value;
        }

        /**
         * Gets the value of the focus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFocus() {
            return focus;
        }

        /**
         * Sets the value of the focus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFocus(String value) {
            this.focus = value;
        }

        /**
         * Gets the value of the implicitFocus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImplicitFocus() {
            return implicitFocus;
        }

        /**
         * Sets the value of the implicitFocus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplicitFocus(String value) {
            this.implicitFocus = value;
        }

    }

}
