//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.24 at 12:04:02 PM CEST 
//


package decomposition.buildgraph;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.Relations }
     * 
     */
    public Document.Relations createDocumentRelations() {
        return new Document.Relations();
    }

    /**
     * Create an instance of {@link Document.Markables }
     * 
     */
    public Document.Markables createDocumentMarkables() {
        return new Document.Markables();
    }

    /**
     * Create an instance of {@link Document.Token }
     * 
     */
    public Document.Token createDocumentToken() {
        return new Document.Token();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link TokenAnchor }
     * 
     */
    public TokenAnchor createTokenAnchor() {
        return new TokenAnchor();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Document.Relations.ENTAILS }
     * 
     */
    public Document.Relations.ENTAILS createDocumentRelationsENTAILS() {
        return new Document.Relations.ENTAILS();
    }

    /**
     * Create an instance of {@link Document.Relations.EQUIVALENT }
     * 
     */
    public Document.Relations.EQUIVALENT createDocumentRelationsEQUIVALENT() {
        return new Document.Relations.EQUIVALENT();
    }

    /**
     * Create an instance of {@link Document.Relations.BEFORE }
     * 
     */
    public Document.Relations.BEFORE createDocumentRelationsBEFORE() {
        return new Document.Relations.BEFORE();
    }

    /**
     * Create an instance of {@link Document.Markables.FOCUS }
     * 
     */
    public Document.Markables.FOCUS createDocumentMarkablesFOCUS() {
        return new Document.Markables.FOCUS();
    }

    /**
     * Create an instance of {@link Document.Markables.FRAGMENT }
     * 
     */
    public Document.Markables.FRAGMENT createDocumentMarkablesFRAGMENT() {
        return new Document.Markables.FRAGMENT();
    }

    /**
     * Create an instance of {@link Document.Markables.MODIFIER }
     * 
     */
    public Document.Markables.MODIFIER createDocumentMarkablesMODIFIER() {
        return new Document.Markables.MODIFIER();
    }

}
